Assert correct class of arrays returned by ivy and frontend functions/methods
ivy-llc/ivy pull request #19183
Opened 2023-07-10 14:53 UTC by AnnaTz

2023-07-20 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-07-24 11:23 UTC, AnnaTz commented
ivy-gardener

2023-07-24 11:29 UTC, CatB1t requested changes

2023-07-24 11:29 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +
We should do similar assertion for return from ground truth.

2023-07-24 11:29 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +
Similar to the case above, we should assert the same for ground truth backend.

2023-07-24 12:15 UTC, CatB1t requested changes

2023-07-24 12:15 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret_from_target, lambda x: ivy.is_ivy_array(x) if ivy.is_array(x) else True
This should be `ret_from_gt`

2023-07-24 12:15 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret_from_target, lambda x: ivy.is_ivy_array(x) if ivy.is_array(x) else True
We shouldn't use the global ivy, we should use the local version from the context manager `gt_backend`

2023-07-24 12:15 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +
similarly we should use the local backend

2023-07-26 08:23 UTC, CatB1t requested changes

2023-07-26 08:23 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret_from_target, lambda x: ivy.is_ivy_array(x) if ivy.is_array(x) else True
`ivy.is_ivy_array()` would be bound to global ivy, which has it's backend unchanged, we should use local Ivy.

2023-07-26 08:23 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret, lambda x: _is_frontend_array(x) if ivy.is_array(x) else True
`ivy.is_array()` would be bound to global ivy, which has it's backend unchanged, we should use local Ivy.

2023-07-26 08:23 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret, lambda x: ivy.is_ivy_array(x) if ivy.is_array(x) else True
`ivy.is_ivy_array()` would be bound to global ivy, which has it's backend unchanged, we should use local Ivy.

2023-07-26 08:23 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +            ret, lambda x: _is_frontend_array(x) if ivy.is_array(x) else True
`ivy.is_array()` would be bound to global ivy, which has it's backend unchanged, we should use local Ivy.

2023-08-12 05:53 UTC, ivy-seed commented
This PR has been labelled as stale because it has been inactive for more than 7 days. If you would like to continue working on this PR, then please add another comment or this PR will be closed in 7 days.

2023-08-14 10:53 UTC, CatB1t approved these changes
lgtm!

2023-08-14 15:32 UTC, merged