Ivy.irfftn
ivy-llc/ivy pull request #21516
Opened 2023-08-09 06:13 UTC by rajveer43

close #19695
close #19681

2023-08-11 13:37 UTC, sherry30 requested changes
requested a few changes.

Can you elaborate what problems are you facing in the tf backend. is the current approach not working?

thanks

2023-08-11 13:37 UTC, sherry30 commented on ivy_tests/test_ivy/test_functional/test_experimental/test_nn/test_layers.py
> +    axes = draw(
you can use the `helpers.arrays_and_axes` helper instead of generating axes separately

2023-08-11 13:37 UTC, sherry30 commented on ivy/functional/ivy/experimental/layers.py
> +def irfftn(
I think you should also add `handle_device_shifting` and `handle_backend_invalid` decorator in the correct order.

2023-09-11 20:37 UTC, xingshuodong commented
@rajveer43 how is your irfftn function going? I am struggling on frontend paddle function, can we have a discussion on the understanding of irfftn speicifc to tf numpy and paddle, if so, please 
contact me on xingshu@deakin.edu.au or discord, in ivy sdxing

2023-10-11 11:52 UTC, closed without merging