function_testing.py docstring update
ivy-llc/ivy pull request #21543
Opened 2023-08-09 14:14 UTC by rajveer43

close #21519
close #21911

2023-08-11 17:17 UTC, theRealBird commented
Hi @rajveer43,
Thank you for your contribution to Ivy. I see that you have started adding docstrings for other functions as well. We appreciate and celebrate your efforts! However, in order for us to keep track of what has been implemented/ what's missing could you please open relevant issues for all of the docstrings which you are adding?

Your changes look good to me! But I will let @CatB1t, take a look once too as the original issue has been assigned to him. Thanks!

2023-08-14 10:49 UTC, CatB1t requested changes

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        etc.
```suggestion
      The backend framework to be tested.
```

Let's not include examples in the docstring for parameter. Let's update the other docstring similarly, Thanks!

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +    args_np : tuple
let's omit the type of the argument

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        Frontend function flags object that stores all testing flags.
```suggestion
        Function Test Flags object that contains test flags to be applied.
```

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        If True, test compilation. (Default value: False)
Let's omit default values.

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        Relative tolerance value for gradient comparison. (Default value: None)
Let's omit default values.

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        Absolute tolerance value for gradient comparison. (Default value: 1e-06)
Let's omit default values.

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +        The device on which to create arrays.
```suggestion
        The device on which to test the function on.
```

2023-08-14 10:49 UTC, CatB1t commented on ivy_tests/test_ivy/helpers/function_testing.py
> +    None
We can remove this.

2023-09-05 10:13 UTC, KareemMAX commented
Hey @rajveer43,
I just checked on this PR. Maybe @sherry30 can take @CatB1t's place. If you don't mind @CatB1t ofc 😅

2023-10-04 05:34 UTC, closed without merging