Added byteswap to numpy frontend
ivy-llc/ivy pull request #24154
Opened 2023-09-18 20:20 UTC by VedangSavadi

Description:

This pull request introduces a  numpy instance method, byteswap, to the ndarray class in the ivy.functional.frontends.numpy.ndarray module. The byteswap method provides the capability to swap the byte order of the data in the ndarray.

Details:

Method Signature:

byteswap(self, inplace=False)
Parameters:

self: The ndarray instance on which this method is called.
inplace (optional, default False): A boolean flag that determines whether the byteswap should be performed in-place or return a new ndarray with swapped bytes.
Functionality:

When inplace is True, the method performs an in-place byteswap operation on the ndarray object.
When inplace is False, the method returns a new ndarray with the byte order swapped.

2023-09-18 20:30 UTC, ivy-leaves commented
If you are working on an open task, please **edit** the PR description to link to the issue you've created.

For more information, please check [ToDo List Issues Guide](https://unify.ai/docs/ivy/overview/contributing/the_basics.html#todo-list-issues).

Thank you :hugs:

2023-09-21 07:52 UTC, VedangSavadi commented
Hi @RickSanchezStoic , waiting for review and feedback. Thank you!

2023-09-22 16:23 UTC, RickSanchezStoic commented
@RashulChutani why it `dill` not being found in the tests even when it's a requirement listed ?

2023-09-30 03:44 UTC, VedangSavadi commented
Hi, @RickSanchezStoic please let me know if any changes are required. Thank you!

2023-10-09 13:46 UTC, RickSanchezStoic commented
@RashulChutani the test function `test_numpy_ndarray_byteswap` isn't getting detected it seems, can you please look into this once? Thanks!

2024-03-04 11:37 UTC, Ishticode commented
pls resolve the conflict and i will take a look at the ci and merge it asap as its a pretty straightforward one

2024-03-04 12:57 UTC, VedangSavadi commented
@Ishticode I have resolved the conflicts now. Thank You

2024-07-11 03:21 UTC, Sam-Armstrong requested changes

2024-07-11 03:21 UTC, Sam-Armstrong commented on ivy/functional/frontends/numpy/ndarray/ndarray.py
> +            return self.ivy_array.byteswap()
There is no `byteswap` method in the ivy api right now, so this frontend function would require a manual implementation using other ivy functions.

2024-07-12 17:55 UTC, closed without merging