feat: Update general_functions.py by adding random_uniform_initializer
ivy-llc/ivy pull request #26970
Opened 2023-10-12 17:43 UTC by tagrib

Close #26962

# PR Description

## Related Issue

Closes #26962

## Checklist

- [+] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2023-10-13 14:51 UTC, tagrib commented
Can you review this PR please.
@Dsantra92

2023-10-13 16:16 UTC, Dsantra92 requested changes

2023-10-13 16:16 UTC, Dsantra92 commented on ivy/functional/frontends/tensorflow/general_functions.py
> +        maxval = 1.0
No need to have the try except here. It will be handled in the backend. Also, you needs to add tests for the given function.

2023-12-26 17:30 UTC, niixxaaa commented
Hey, can you solve the merge conflicts?
Thanks!

2024-07-11 21:20 UTC, closed without merging