Added Wasserstein Loss, the Most Popular Loss Function for GANs
ivy-llc/ivy pull request #27207
Opened 2023-11-04 01:25 UTC by hi-sushanta

Introducing the Wasserstein loss function - the crown jewel of GANs! This state-of-the-art loss function helps both the generator and discriminator reach new heights of performance. The results? Stunningly realistic generated images that even the most discerning eye would mistake for the real thing. It's like magic, but with math! 🎩

**Here is my code!**
![Screenshot (10)](https://github.com/unifyai/ivy/assets/93595990/cfd9fa47-453d-4c92-ba50-ad82798ae3c3)

## Checklist

- [x] Did you add a function?
- [ ] Did you add the tests?
- [x] Did you run your tests and are your tests passing?
- [x] Did pre-commit not fail on any check?
- [x] Did you follow the steps we provided?

2023-11-05 00:37 UTC, hi-sushanta commented
Does anyone see my changes?

2023-11-08 00:41 UTC, hi-sushanta commented
I believe that the community around this repository is no longer active, so I have decided to delete it.

2023-12-26 17:04 UTC, niixxaaa commented
Hi, you need to add a hypothesis test in this file `ivy/ivy_tests/test_ivy/test_functional/test_nn/test_losses.py` for the function you've created. 
Thanks :)

2024-03-31 03:47 UTC, Ishticode requested changes
Hi @hi-sushanta 
THank you very much for the effort put into this PR. Apologies for lack of correspondence you have received here. 
The two tests that you have added seem to be failing as maybe seen in the logs here https://github.com/unifyai/ivy/actions/runs/8130590086/job/22219132685?pr=27207
under combined test results. For example, test dic wl has a simple failure such as AttributeError: 'list' object has no attribute 'is_integer'. If you are able to fix these issues, please request my review and I should be able to come back to you quickly. Thank you very much for your patience 🙂

2024-04-02 16:09 UTC, Ishticode requested changes
it was in the ci as seen here
![image](https://github.com/unifyai/ivy/assets/53497039/c63fb5e8-2d6a-4715-bcf9-86ed3db40208)
I think it is due to the way the input dtypes are put in the tests as pointed for test_disc_wl below.

2024-04-02 16:09 UTC, Ishticode commented on ivy_tests/test_ivy/test_functional/test_nn/test_losses.py
> +        input_dtypes=[dtype_p_real, dtype_p_fake],
you should try this as `dtype_p_real + dtype_p_fake`

2024-04-02 16:11 UTC, Ishticode commented
HI. As you can see the is_integer issue is not directly in your code but it comes from how your test expected dtypes to be passed. It should not be a list of lists. You should be able to run tests locally and see these issues easily. Thanks

2024-07-13 16:26 UTC, Sam-Armstrong approved these changes

2024-07-13 16:26 UTC, merged