feat: created func for bilinear
ivy-llc/ivy pull request #28193
Opened 2024-02-05 18:24 UTC by Sanjay8602

# PR Description

## Related Issue

Closes #21366 

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

### Socials

2024-02-11 18:00 UTC, Sanjay8602 reviewed
Deleted import line for bilinear function in test_common

2024-02-21 03:09 UTC, Sarvesh-Kesharwani requested changes

2024-02-21 20:10 UTC, Sanjay8602 commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +    ),
Sure I have taken note of it within next 2 days I will sove it

2024-02-27 06:47 UTC, Sanjay8602 commented
Hey @Sarvesh-Kesharwani please review this changes

2024-02-27 11:34 UTC, Sarvesh-Kesharwani requested changes

2024-02-27 11:34 UTC, Sarvesh-Kesharwani commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +    dtype, x1, x2, weight, bias = dtype_x1_x2_weight_bias
dtype_and_values helper function return max 3 values,
please check the definition of it and use the appropriate helper function for generating the test data.

2024-02-27 11:34 UTC, Sarvesh-Kesharwani commented on ivy_tests/test_ivy/test_frontends/test_paddle/test_nn/test_functional/test_common.py
> +    dtype, x1, x2, weight, bias = dtype_x1_x2_weight_bias
![image](https://github.com/unifyai/ivy/assets/22115102/4d64f690-49b0-4722-b448-deb330a17760)

2024-03-03 11:28 UTC, Sarvesh-Kesharwani commented
![image](https://github.com/unifyai/ivy/assets/22115102/ce51166e-3ff4-45df-a770-32c5e13ea6ed)
Hi @Mr-Array22,
the issue is still not resolved, please go through the shown error again.
![image](https://github.com/unifyai/ivy/assets/22115102/0a2243e7-6995-4f08-af30-228486d37263)

2024-03-03 18:11 UTC, Sanjay8602 commented
> ![image](https://private-user-images.githubusercontent.com/22115102/309546081-ce51166e-3ff4-45df-a770-32c5e13ea6ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODk3MDksIm5iZiI6MTcwOTQ4OTQwOSwicGF0aCI6Ii8yMjExNTEwMi8zMDk1NDYwODEtY2U1MTE2NmUtM2ZmNC00NWRmLWE3NzAtMzJjNWUxM2VhNmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZTU4M2FjNjgzMjkyMjgwZDRiNzcyMjMxYjVmMTA3MGIwZGJhMTJmZTQzNzZhN2IwZTdhNTAyMzM5ZDQxNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TNDw1U8DbFvx-QMWEj8-n1CqveWhjbzMorIq0V91li4) Hi @Mr-Array22, the issue is still not resolved, please go through the shown error again. ![image](https://private-user-images.githubusercontent.com/22115102/309546139-0a2243e7-6995-4f08-af30-228486d37263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODk3MDksIm5iZiI6MTcwOTQ4OTQwOSwicGF0aCI6Ii8yMjExNTEwMi8zMDk1NDYxMzktMGEyMjQzZTctNjk5NS00ZjA4LWFmMzAtMjI4NDg2ZDM3MjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDE4MTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZGRlYTUyNjc4YjIzMjkwNzliNDg2OTVjZDc1NzJhMTMyNmViMzExNzIyZGM1ZWQ5ZjE3NmQxMmRiZDRiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYUWX57rUxzL38p_TpB3fS5ntBPm7gd6EDmUleyDvmg)

My name is Sanjay and whom did you tag I didnt get it

2024-03-14 05:17 UTC, Sanjay8602 commented
Trying to solve it

On Thu, Mar 14, 2024, 10:43 Ishtiaq Hussain ***@***.***>
wrote:

> Hi @Sanjay8602 <https://github.com/Sanjay8602>
> Were you able to resolve the issue pointed out by @Sarvesh-Kesharwani
> <https://github.com/Sarvesh-Kesharwani>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/unifyai/ivy/pull/28193#issuecomment-1996531835>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A43TAWPEWH6GSN4TSRLXKEDYYEWZFAVCNFSM6AAAAABC2T5CFGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOJWGUZTCOBTGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-07-13 16:33 UTC, closed without merging