feat: Implement LabelEncoder methods and add fit method test
ivy-llc/ivy pull request #28702
Opened 2024-03-29 07:25 UTC by muzakkirhussain011

### Enhancements to LabelEncoder for String-to-Numeric Encoding

This PR introduces enhancements to the `LabelEncoder` class, enabling the conversion of string labels into numerical identifiers. Due to the limitation of `ivy.array` not accepting string elements, we've utilized the list data type for encoding operations, ensuring compatibility across all backends.

#### Key Updates:
- **String Handling:** The `LabelEncoder` now uses lists to process and encode string objects into numerical identifiers, circumventing the limitations of `ivy.array`.
- **Backend Compatibility:** The use of lists ensures that our `LabelEncoder` is accessible and functional across various computational backends.
- **Testing Rigor:** The `fit` method tests are consistently passing, affirming the reliability of the foundational fitting process.
- **Method Prerequisites:** Current test failures for `transform`, `fit_transform`, and `inverse_transform` methods are attributed to the prerequisite that the encoder must be fitted prior to these operations. This is a known issue and is being addressed.
- **Manual Verification:** Despite automated test challenges, manual testing of `transform` and `fit_transform` methods with direct input has been successful, demonstrating the methods' proper functionality.

#### Attachments:
- Screenshot of the `fit` method test passing.
- Screenshot of the `transform` method test failing.
- Screenshot of the manual test for `transform` and `fit_transform` methods passing.

This PR lays the groundwork for more robust and versatile encoding capabilities within our machine learning toolkit. By addressing backend compatibility and enhancing the encoder's functionality, we're setting the stage for more advanced features and seamless integration in diverse computational environments.

Closes #

## Checklist

- [ ] Did you add a function?
- [ ] Did you add the tests?
- [ ] Did you run your tests and are your tests passing?
- [ ] Did pre-commit not fail on any check?
- [ ] Did you follow the steps we provided?

![image](https://github.com/unifyai/ivy/assets/138936198/923f9b44-3676-46f4-9f8a-2356c6891e28)
![image](https://github.com/unifyai/ivy/assets/138936198/231d768d-62cb-4fb4-a39f-d1105ed37ba1)
![image](https://github.com/unifyai/ivy/assets/138936198/e543005b-2a95-4595-a1e4-61b417e6f32b)

2024-03-29 09:25 UTC, muzakkirhussain011 commented
Hi @Ishticode ,

Could you please review the “Enhancements to LabelEncoder” PR? Your feedback would be invaluable.

Thanks

2024-03-29 16:51 UTC, Ishticode requested changes
Thank you very much @muzakkirhussain011 
We should not really be adding docstring to the frontends as the actual native frameworks explain the function or classes exactly. You can see this as a NOTE on our frontends guide at https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html. Let me know if something is unclear. Thank you very much

2024-03-29 17:02 UTC, muzakkirhussain011 commented
> Thank you very much @muzakkirhussain011 We should not really be adding docstring to the frontends as the actual native frameworks explain the function or classes exactly. You can see this as a NOTE on our frontends guide at https://unify.ai/docs/ivy/overview/deep_dive/ivy_frontends.html. Let me know if something is unclear. Thank you very much

Hi @Ishticode ,

I acknowledge the frontend documentation standards as highlighted in the guide and will ensure compliance moving forward. Thank you for bringing this to my attention.

Best regards

2024-04-08 04:08 UTC, Ishticode requested changes
Hi. Can we test for newly implemented functions which remove the NotImplementedError. Thansk :)

2024-04-08 04:24 UTC, muzakkirhussain011 commented
Hi @Ishticode ,
The tests for transform, fit_transform, and inverse_transform methods are failing because these methods require the LabelEncoder to be fitted with data first. This prerequisite is not currently met within the automated testing setup, leading to failures.

Manual Verification: Manual testing of the transform and fit_transform methods with direct input has been successful, indicating that the methods function correctly when the encoder is properly fitted.

I have attached Screenshot of the fit method test passing.

Screenshot of the transform method test failing.

Screenshot of the manual test for transform and fit_transform methods passing.

In the PR description.

2024-04-09 04:36 UTC, Ishticode requested changes
Sure, in that case we should still add the test but make a fit call before calling the actual test call. :)

2024-04-17 07:23 UTC, muzakkirhussain011 commented
Hi @Ishticode ,
Even though I called the fit method beforehand I'm still getting the not fitted error.

Test for transform method:
```
@handle_frontend_method(
    class_tree=CLASS_TREE + ".LabelEncoder",
    init_tree="sklearn.preprocessing.LabelEncoder",
    method_name="transform",
    dtype_x=helpers.dtype_and_values(
        available_dtypes=helpers.get_dtypes("float_and_integer"),
        min_num_dims=1,
        max_num_dims=1,
    ),
)
def test_sklearn_label_encoder_transform(
    dtype_x,
    frontend,
    frontend_method_data,
    init_flags,
    method_flags,
    on_device,
    backend_fw,
):
    input_dtype, x = dtype_x
    # Initialize the LabelEncoder and fit it with the input data
    encoder = LabelEncoder()
    encoder.fit(x[0])

    helpers.test_frontend_method(
        init_input_dtypes=input_dtype,
        init_all_as_kwargs_np={},
        method_input_dtypes=input_dtype,
        method_all_as_kwargs_np={
            "y": x[0],
        },
        frontend_method_data=frontend_method_data,
        init_flags=init_flags,
        method_flags=method_flags,
        frontend=frontend,
        on_device=on_device,
        backend_to_test=backend_fw,
    )

```


Output of the test:
![image](https://github.com/unifyai/ivy/assets/138936198/aae1d8f3-d735-4b5b-85ae-cbde965565f1)

2024-08-07 02:56 UTC, muzakkirhussain011 commented
Hi @Ishticode,
hope you're doing well! I wanted to kindly remind you that this PR has been awaiting your review for 4 months now. Your feedback is greatly appreciated, and I'm looking forward to hearing your thoughts when you have a moment to spare.
Thank you 
Best regards

2024-08-08 13:27 UTC, muzakkirhussain011 commented
Hi @Ishticode ,
hope you're doing well! I wanted to kindly remind you that this PR has been awaiting your review for 4 months now. I have added the tests as mentioned above. Your feedback is greatly appreciated, and I'm looking forward to hearing your thoughts when you have a moment to spare.
Thank you
Best regards

2024-08-08 16:00 UTC, muzakkirhussain011 commented
Hi @Sam-Armstrong  ,
hope you're doing well! I wanted to kindly remind you that this PR has been awaiting your review for 4 months now. I have added the tests as mentioned above. Your feedback is greatly appreciated, and I'm looking forward to hearing your thoughts when you have a moment to spare.
Thank you
Best regards

2024-08-08 16:13 UTC, Sam-Armstrong requested changes
Apologies for the slow review on this! The tests you wrote are all failing, please can you fix them? You can follow the precedent of the first test in this file.

`pytest ivy_tests/test_ivy/test_frontends/test_sklearn/test_preprocessing/test_label.py`

2024-08-08 16:13 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_sklearn/test_preprocessing/test_label.py
> +    encoder.fit(x[0])
You shouldn't be initializing a LabelEncoder here; see the first test in this file as an example of how to write the test.

2024-08-08 16:15 UTC, muzakkirhussain011 commented
Hi @Sam-Armstrong ,
The tests for transform, fit_transform, and inverse_transform methods are failing because these methods require the LabelEncoder to be fitted with data first. This prerequisite is not currently met within the automated testing setup, leading to failures.

Manual Verification: Manual testing of the transform and fit_transform methods with direct input has been successful, indicating that the methods function correctly when the encoder is properly fitted.

I have attached Screenshot of the fit method test passing.

Screenshot of the transform method test failing.

Screenshot of the manual test for transform and fit_transform methods passing.

In the PR description.

2024-08-08 17:25 UTC, Sam-Armstrong requested changes
Ok sure, that's fine. Considering the sklearn frontend is low-priority right now, I think we don't have to worry about modifying the testing infrastructure to get these working. Please could you leave todo notes on the tests as I've indicated below, then we can get this merged. Thanks!

2024-08-08 17:25 UTC, Sam-Armstrong commented on ivy_tests/test_ivy/test_frontends/test_sklearn/test_preprocessing/test_label.py
> +    )
```suggestion
    # TODO: add test for this method with encoder already fitted with data
    pass
```

2024-08-08 18:12 UTC, muzakkirhussain011 commented
Done. I've added the todo notes on the tests as requested. The modifications to the testing infrastructure can be addressed later, given the low priority of the sklearn frontend. I've completed the tasks and the changes are ready to be merged. Let me know if there's anything else I can assist with.

2024-08-10 12:39 UTC, muzakkirhussain011 commented
Hi @Sam-Armstrong ,
I wanted to follow up and confirm that the requested changes, including the addition of the todo notes, have been implemented as per your instructions. Please let me know if there's anything else you need. Thank you.

2024-08-10 16:13 UTC, Sam-Armstrong approved these changes
Thanks @muzakkirhussain011, will merge now 😄

2024-08-10 16:14 UTC, merged