Add conv_transpose to tensorflow frontend
ivy-llc/ivy pull request #4421
Opened 2022-09-13 15:12 UTC by Change-m

Close #4420

2022-09-14 05:03 UTC, VedPatwardhan requested changes

2022-09-14 05:03 UTC, VedPatwardhan commented on ivy/functional/frontends/tensorflow/nn.py
> +    return ivy.conv_transpose( input, filters, output_shape, strides, padding, data_format=data_format, dilations=dilations)
I don't think there's a `conv_transpose` function in Ivy's functional API, so either you'll have to implement the `tensorflow` `conv_transpose` frontend as a composition of existing Ivy functions or extend Ivy's functional API by adding `ivy.conv_transpose` in a separate PR referring to the [docs](https://lets-unify.ai/ivy/contributing/4_open_tasks.html#ivy-api-extensions)

2022-09-14 12:03 UTC, Change-m commented
Hi @VedPatwardhan, Please re-review the PR.

2022-09-15 06:40 UTC, VedPatwardhan requested changes
Hi @Change-m, the `conv_transpose` seems to be a general implementation of transpose convolutions which doesn't exist in the codebase. I think you'll have to add that function as an extension to Ivy in a separate PR. 
Let me know if you have any questions. Thanks 🙂

2022-09-15 06:40 UTC, VedPatwardhan commented on ivy/functional/ivy/layers.py
> +def conv_transpose(
I think rather than adding a `conv_transpose` function here, you should either add it in a separate PR along with their backend implementations.

2022-09-15 09:04 UTC, closed without merging