Added instance of mean for numpy frontend
ivy-llc/ivy pull request #6270
Opened 2022-10-28 14:23 UTC by Hassan-Ik

2022-10-31 10:05 UTC, AnnaTz commented
Hi there, if this is part of a ToDo list issue, could you please make a comment "Close #issue_number" to link it?

2022-10-31 10:14 UTC, AnnaTz requested changes
Please be careful to not commit changes in the `.idea` folder. You should rollback the 3 `.xml` files.

2022-10-31 10:14 UTC, AnnaTz commented on ivy_tests/test_ivy/test_frontends/test_numpy/test_ndarray/test_ndarray.py
> +        fn_name="ivy.functional.frontends.numpy.ndarray.mean"
The test fails with `AttributeError: module 'ivy.functional.frontends.numpy.ndarray' has no attribute 'mean'`. I think the `fn_name` should be `ivy.functional.frontends.numpy.ndarray.ndarray.mean`. 
You can check out errors by clicking `Details` next to 
`test-frontend-numpy / run-nightly-tests (pull_request)`. Then you should expand `Run Frontend Tests` and search for your test's name.

2022-10-31 12:13 UTC, closed without merging

2022-11-01 09:17 UTC, AnnaTz commented
Hi there, the PR was almost ready! Why did you close it?

2022-11-01 09:23 UTC, Hassan-Ik commented
Yes, Sorry about that actually I reverted commits and pushed those changes on remote git repo too due to which my PR was closed.

2022-11-01 09:23 UTC, Hassan-Ik commented
Yes, Sorry about that actually I reverted commits and pushed those changes on remote git repo too due to which my PR was closed.